# Setup
name:         Tech Corner
tagline:      Devops-GitHub & IaC-Terraform
domain:       mvuddaraju.github.io 
#baseurl:      ""
locale:       "en"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
